services:
  ai-service-go:
    container_name: ai-service-go
    image: rishaveeplus/ai-service-go
    env_file:
      - .env
    depends_on:
      - qdrant
    volumes:
      - ./public:/app/public:ro
      - ./data/data.txt:/app/data.txt:ro
      - ./data/data.json:/app/data.json:ro
      - ./logs:/logs/ai-service
    restart: unless-stopped
    networks:
      - internal_api_network

  qdrant:
    image: qdrant/qdrant:v1.16
    container_name: qdrant2
    volumes:
      - ./qdrant_storage:/qdrant/storage
    networks:
      - internal_api_network
    restart: unless-stopped

  ai_service_db:
    container_name: ai_service_db
    image: postgres:14
    environment:
      POSTGRES_USER: ${CHAT_DB_USER}
      POSTGRES_PASSWORD: ${CHAT_DB_PASSWORD}
      POSTGRES_DB: ${CHAT_DB_NAME}
    volumes:
      - ai_service_db_data:/var/lib/postgresql/data
    networks:
      - internal_api_network
    restart: unless-stopped

networks:
  internal_api_network:
    external: true

volumes:
  qdrant_storage:
  ai_service_db_data:
  
